[databricks]
dir_path="/dbfs/FileStore/tables/Ashutosh"
cluster_id="0113-052453-kes2syt7"
run_name="prefect-job"
notebook_path="/Repos/agoyal@sigmoidanalytics.com/Prefect_Databricks_Assignment/Tasks"

[api]
host="vaccovid-coronavirus-vaccine-and-treatment-tracker.p.rapidapi.com"
url_head="https://${api.host}/api/npm-covid-data/country-report-iso-based"
countries="USA,India,France,Germany,Brazil,S. Korea,UK,Italy,Japan,Russia,Turkey,Spain,Vietnam,Australia,Argentina,Netherlands,Taiwan,Iran,Mexico,Indonesia"
iso_code="usa,ind,fra,deu,bra,kor,gbr,ita,jpn,rus,tur,esp,vnm,aus,arg,nld,twn,irn,mex,idn"
